bus/fslmc: fix const pointer in device name parsing
[ upstream commit f4ef899bb3aeca2fa195f9605ddaf7567f8b0afb ]

With latest glibc (Fedora Rawhide):
drivers/bus/fslmc/fslmc_bus.c: In function ‘rte_fslmc_parse’:
drivers/bus/fslmc/fslmc_bus.c:298:15: error:
assignment discards ‘const’ qualifier from pointer target type
   298 |         t_ptr = strchr(sep, '.');
       |               ^

Fixes: e67a61614d0b ("bus/fslmc: support device iteration")

Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
Acked-by: Hemant Agrawal <hemant.agrawal@nxp.com>
Acked-by: David Marchand <david.marchand@redhat.com>