rcu: fix build with MSVC
[ upstream commit d1ab1a2facf9b823bc400e573aa39381ca7b915f ]

Within GitHub actions, with MSVC 19.44.35219,
the following error can be reported:

...\rte_rcu_qsbr.h(566): error C2220:
	the following warning is treated as an error
...\rte_rcu_qsbr.h(566): warning C4319:
	'~': zero extending 'unsigned long' to 'uint64_t' of greater size

To fix this, replace the "1UL" with RTE_BIT64 to force a 64-bit value
on all platforms.

Fixes: 64994b56cfd7 ("rcu: add RCU library supporting QSBR mechanism")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>